language: ruby
cache: 
  - bundler
  - directories:
    - $TRAVIS_BUILD_DIR/tmp/.htmlproofer
rvm:
- 2.3.3

script: bundle exec jekyll build && bundle exec htmlproofer --assume-extension --timeframe '30d' ./_site

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

sudo: false
