name: Pauli Lab
motto: Investigating new regulators of embryogenesis
author: Tomas Kazmar
url: http://paulilab.org/
meta_description: developmental biology, zebrafish, RNA-seq, ribosome profiling, lightsheet imaging, short proteins, Elabela, Apela, Toddler, embryogenesis
permalink: /:year/:month/:day/:title/
exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - 'Gruntfile.js'
  - 'README.md'
  - 'TODO.md'
  - '_config.yml'
  - 'assets/img/README.md'
  - 'bundle'
  - 'js'
  - 'less'
  - 'node_modules'
  - 'package.json'
  - 'tools'
  - 'vendor'
include: ['_pages']
years: [2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004]
markdown: kramdown
excerpt_separator: <!--more-->
collections:
  pubs:
    output: false
    permalink: /pubs/:path/
  people:
    output: false
    permalink: /people/:path/
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
