name: Pauli Lab
motto: Investigating new regulators of embryogenesis
author: Tomas Kazmar
url: http://paulilab.org
meta_description: Pauli Lab investigates regulators of embryogenesis @ Research Institute of Molecular Pathology (IMP), Vienna Biocenter.
twitter: andreapauli77
default_splash: /assets/img/splash-fish.jpg
include: ['_pages']
years: [2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004]
permalink: /:year/:month/:day/:title/
exclude:
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - README.md
  - TODO.md
  - _config.yml
  - assets/img/README.md
  - bundle
  - js
  - less
  - node_modules
  - package.json
  - tools
  - resources
  - vendor
gems: # XXX:because of github's old version
  - jekyll-sitemap
plugins:
  - jekyll-sitemap
markdown: kramdown
excerpt_separator: <!--more-->
collections:
  pubs:
    output: false
    permalink: /pubs/:path/
  people:
    output: false
    permalink: /people/:path/
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
