name: Pauli Lab
motto: How life starts: mechanistic insights into the oocyte-to-embryo transition
author: Tomas Kazmar
url: http://paulilab.org
social:
  twitter: andreapauli77
  instagram: pauli.lab
  # youtube, facebook, instagram...
default_splash: /assets/img/splash/fish.jpg
location:
  latitude: 48.189413
  longitude: 16.402834
  street: Campus-Vienna-Biocenter 1
  city: Vienna
  country: Austria
  postal_code: A-1030
include: ['_pages']
years: [2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004]
permalink: /news/:year-:month-:day-:title/
exclude:
  - Gemfile
  - Gemfile.lock
  - Gruntfile.js
  - README.md
  - TODO.md
  - _config.yml
  - assets/img/README.md
  - js
  - less
  - node_modules
  - package.json
  - tools
  - resources
  - vendor
plugins:
  - jekyll-sitemap
markdown: kramdown
excerpt_separator: <!--more-->
collections:
  pubs:
    output: false
    permalink: /pubs/:path/
  people:
    output: false
    permalink: /people/:path/
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
